CREATE TABLE app_user (
                          id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username  VARCHAR(255) NOT NULL UNIQUE,
                          password  VARCHAR(255) NOT NULL,
                          enabled   BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE app_user_roles (
                                user_id  BIGINT NOT NULL REFERENCES app_user (id),
                                role     VARCHAR(255) NOT NULL,
                                PRIMARY KEY (user_id, role)
);